### ISSUE TITLE
How to use KAFKA_PREFIX without Multi-Tenant add-on

### ISSUE THREAD

**Issue by codaksh001** [karafka/karafka-web#311]
Versions
Ruby: 3.3.0
Rails: 7.1.3
Karafka: 2.3.3
Karafka-web: 0.8.2

I have started using Karafka Gem in my Rails application, which is usually a multitenant application. Currently, I am working on my local machine
 I have added the below configuration for the **Karafka-web** dashboard but I am getting an error
```
Karafka::Web.setup do |config|
  # env_suffix = "#{ENV['TENANT_NAME'] || ENV['RAILS_ENV']}"
  # You may want to set it per ENV. This value was randomly generated.
  config.ui.sessions.secret = ENV.fetch('KARAFKA_SESSIONS_SECRET','*********')

  config.topics.errors = "#{ENV['KAFKA_PREFIX']}_karafka_errors"
  config.topics.consumers.reports = "#{ENV['KAFKA_PREFIX']}_karafka_consumers_reports"
  config.topics.consumers.states = "#{ENV['KAFKA_PREFIX']}_karafka_consumers_states"
  config.topics.consumers.metrics = "#{ENV['KAFKA_PREFIX']}_karafka_consumers_metrics"
end

Karafka::Web.enable!
```
Error logs

```
[41d7cf27a88d] Polled 26 messages in 1254.6510000005364ms
[bdee5edf9354] Consume job for Karafka::Web::Processing::Consumer on tenant_name_karafka_consumers_reports/0 started
Consumer consuming error: Karafka::Web::Errors::Processing::MissingConsumersStatesTopicError
***_application_path/gems/karafka-web-0.8.2/lib/karafka/web/processing/consumers/state.rb:29:in `rescue in current!'
***_application_path/gems/karafka-web-0.8.2/lib/karafka/web/processing/consumers/state.rb:13:in `current!'
***_application_path/gems/karafka-web-0.8.2/lib/karafka/web/management/migrator.rb:107:in `consumers_state'
***_application_path/gems/karafka-web-0.8.2/lib/karafka/web/management/migrator.rb:55:in `ensure_migrable!'
***_application_path/gems/karafka-web-0.8.2/lib/karafka/web/management/migrator.rb:44:in `call'
***_application_path/gems/karafka-web-0.8.2/lib/karafka/web/processing/consumer.rb:84:in `bootstrap!'
***_application_path/gems/karafka-web-0.8.2/lib/karafka/web/processing/consumer.rb:16:in `consume'
***_application_path/gems/karafka-2.3.3/lib/karafka/processing/strategies/default.rb:111:in `block in handle_consume'
***_application_path/gems/karafka-core-2.3.0/lib/karafka/core/monitoring/notifications.rb:122:in `measure_time_taken'
***_application_path/gems/karafka-core-2.3.0/lib/karafka/core/monitoring/notifications.rb:98:in `instrument'
***_application_path/gems/karafka-core-2.3.0/lib/karafka/core/monitoring/monitor.rb:34:in `instrument'
***_application_path/gems/karafka-2.3.3/lib/karafka/processing/strategies/default.rb:110:in `handle_consume'
***_application_path/gems/karafka-2.3.3/lib/karafka/base_consumer.rb:70:in `on_consume'
***_application_path/gems/karafka-2.3.3/lib/karafka/processing/executor.rb:83:in `consume'
***_application_path/gems/karafka-2.3.3/lib/karafka/processing/jobs/consume.rb:35:in `call'
***_application_path/gems/karafka-2.3.3/lib/karafka/processing/worker.rb:63:in `block in process'
***_application_path/gems/karafka-core-2.3.0/lib/karafka/core/monitoring/notifications.rb:122:in `measure_time_taken'
***_application_path/gems/karafka-core-2.3.0/lib/karafka/core/monitoring/notifications.rb:98:in `instrument'
***_application_path/gems/karafka-core-2.3.0/lib/karafka/core/monitoring/monitor.rb:34:in `instrument'
***_application_path/gems/karafka-2.3.3/lib/karafka/processing/worker.rb:54:in `process'
***_application_path/gems/karafka-2.3.3/lib/karafka/processing/worker.rb:37:in `block in call'
<internal:kernel>:187:in `loop'
***_application_path/gems/karafka-2.3.3/lib/karafka/processing/worker.rb:37:in `call'
***_application_path/gems/karafka-2.3.3/lib/karafka/helpers/async.rb:37:in `block (2 levels) in async_call'
[32b210d2f144] Pausing on topic tenant_name_karafka_consumers_reports/0 on offset 102
[e31265835d47] Retrying of Karafka::Web::Processing::Consumer after 30000 ms on topic tenant_name_karafka_consumers_reports/0 from offset 102
```

how can I customize the metrics topic name according to my tenant environment in Karafka::Web.setup

**Comment by mensfeld** [comment]
`MissingConsumersStatesTopicError` indicates you did not follow https://karafka.io/docs/Web-UI-Getting-Started/ correctly. You are missing necessary topics.

> how can I customize the metrics topic name according to my tenant environment in Karafka::Web.setup

This does not work that way. All apps in a multi-tenant report to one UI.

Also please keep in mind, that karafka supports multi-app and NOT multi-tenant. I'm not exactly sure what you even mean by multi-tenant in that case and I went with the assumption you meant multi-app

**Comment by mensfeld** [comment]
a you see, you did not specify that you mean heroku.

Heroku instructions are here: https://karafka.io/docs/Deployment/#heroku

You can reconfigure the web UI accordingly: https://karafka.io/docs/Web-UI-Configuration/

**Comment by codaksh001** [comment]
Thanks for your quick response.

multi-tenant means multiple application
It means we are using the same KAFKA_BROKER for multiple applications and they all are deployed to AWS.
Each application has its own topics which are created using the application tenant_name as a prefix 

Now I want every application should have its own karafka dashboard using the same KAFKA_BROKER
I thought if I could customize the below config according to application tenant_name.
After adding the below code in `karafka.rb` started getting the above error

Karafka::Web.setup do |config|
  config.topics.errors = "#{ENV['KAFKA_PREFIX']}_karafka_errors"
  config.topics.consumers.reports = "#{ENV['KAFKA_PREFIX']}_karafka_consumers_reports"
  config.topics.consumers.states = "#{ENV['KAFKA_PREFIX']}_karafka_consumers_states"
  config.topics.consumers.metrics = "#{ENV['KAFKA_PREFIX']}_karafka_consumers_metrics"
end

And when I commented above code everything started working fine.

**Comment by mensfeld** [comment]
such support is beyond my OSS support per my policy: https://karafka.io/docs/Problems%2C-Troubleshooting-and-Debugging/#oss-support-policy

I would get into the weeds of your setup and spend time understanding what exactly you want to achieve, how deployment should work, etc. I am sorry but I will not be able to provide you free support for such sophisticated case. It would require big time investment on my side. If you need this and for your company operations, please consider getting the commercial support.
