### ISSUE TITLE
Ruby 3.4.0 preview1 - No such file or directory

### ISSUE THREAD

**Issue by BrandonHicks-msr** [karafka/karafka-web#343]
*Be clear, concise and precise in your description of the problem.
Open an issue with a descriptive title and a summary in grammatically correct,
complete sentences.*

*Use the template below when reporting bugs. Please, make sure that
you're running the latest stable Karafka and that the problem you're reporting
hasn't been reported (and potentially fixed) already.*

*Before filing the ticket you should replace all text above the horizontal
rule with your own words.*

--------

## Expected behavior

The Karafka UI to display as expected with ruby `3.4.0-preview1` except it errors out. When running in `3.3.1` it works as expected.

## Actual behavior

Switching directly from Ruby `3.3.1` to `3.4.0-preview1` throws a "No such file or directory" exception on the UI views loaded.
Based on the error it appears the class is being processed as the file name `karafka/web/ui/views/dashboard/Karafka::Web::Ui::Controllers::DashboardController#index.erb`

<img width="1289" alt="Screenshot 2024-05-28 at 6 56 54 AM" src="https://github.com/karafka/karafka-web/assets/110928995/1f5543be-f0e3-430d-9dc8-145b11e7c548">

## Steps to reproduce the problem

Rails: `7.1.3.3`
Ruby: `3.4.0preview1`
Karafka: `2.4.2`

A very basic setup of karafka in the rails app, with ruby `3.3.1` it works as expected. But once updated to `3.4.0-preview1` it throws errors when loading karfaka UI.

## Your setup details

Please provide kafka version and the output of `karafka info` or `bundle exec karafka info` if using Bundler.

Here's an example:

```
$ [bundle exec] karafka info
Karafka version: 2.4.2
Ruby version: ruby 3.4.0preview1 (2024-05-16 master 9d69619623) [arm64-darwin23]
Rdkafka version: 0.15.1
Consumer groups count: 1
Subscription groups count: 1
Workers count: 5
Application client id: app_api
Boot file: /Users/brandonhicks/app_api/karafka.rb
Environment: development
```

**Comment by mensfeld** [comment]
Yeah. It seems route path resolution has changed due to... something ;) I will take a look at it but ain't my biggest priority.

**Comment by mensfeld** [comment]
@BrandonHicks-msr I can reproduce. It seems to be an issue in roda. I will handle this.
