### ISSUE TITLE
Report messages production pace in a non-cumulative way in the dashboard

### ISSUE THREAD

**Issue by mensfeld** [karafka/karafka-web#352]

**Comment by 9mm** [comment]
![](https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExeW94a2Rhcjh5czR4bmFqeTA5NWRmcGpsejBjbnF5Z25xcjM0ODgyMiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/l0Exnza7Inc793H0Y/giphy.webp)
