### ISSUE TITLE
undefined method `deep_merge' for an instance of Hash

### ISSUE THREAD

**Issue by edenisn** [karafka/karafka-web#430]
```ruby
merged_params = request.params.deep_merge(query_data)
```
undefined method `deep_merge' for an instance of Hash (NoMethodError)

Ruby | /usr/local/bundle/gems/karafka-web-0.10.1/lib/karafka/web/ui/base.rb: in block in <class:Base>, line 136
GET localhost/jobs/running

--------

## Steps to reproduce the problem

Those behavior on pages: /cluster, /routing, /jobs/running

## Your setup details

One important thing: There are no Karafka consumer processes actively reporting to the Web UI.

```
$ [bundle exec] karafka info
Ruby version: ruby 3.3.3 (2024-06-12 revision f1c7b6f435) [x86_64-linux-musl]
Rdkafka version: 0.17.3
Consumer groups count: 1
Subscription groups count: 1
Workers count: 5
Application client id: karafka
Boot file: /usr/opt/karafka-web-ui/karafka.rb
Environment: development
License: LGPL-3.0
```

**Comment by mensfeld** [comment]
Please fill this:

> Steps to reproduce the problem

**Comment by mensfeld** [comment]
ah no need. deep merge is part of activesupport. You can add it now as a dependency and I will remove it in the next release.

**Comment by edenisn** [comment]
@mensfeld thx!
