### ISSUE TITLE
Visually distinguish karafka-web running in different environments

### ISSUE THREAD

**Issue by technicalpickles** [karafka/karafka-web#433]
## Is your feature request related to a problem? Please describe.

We have multiple environments we run karafka in. Most of our tools have a way to visually signifiy what environment they are, ie color of the top bar and/or some text.

## Describe the solution you'd like

I'd like a way to be able to configure something to look different in different environments. We typically use top bar color + text, but open to other ideas.

Ideally, this is something that is configured, rather than inferred, since we have multiple deployments with RAILS_ENV=production that we have other means to determine which "environment" we are in.

## Describe alternatives you've considered

Do nothing: just hope people realize what they are doing before they do it... but from experience, we've had accidents _even with_ visual cues, but it is less than would happen otherwise.

**Comment by mensfeld** [comment]
How would you like it to be configured?

I understand you have `RAILS_ENV=production` in many places so I can imagine something else would be better but I wonder what. Ideally I guess some sort of an alert space that would be displayed on top? Do you have any examples?

**Comment by technicalpickles** [comment]
> I understand you have RAILS_ENV=production in many places so I can imagine something else would be better but I wonder what. 

We actually don't 😁   We have 3 deployments that are RAILS_ENV=production, which is why we can't just check that. We have other environment variables like `APP_ENV`.

>  Do you have any examples?

Yeah, this is the topbar of staging vs production

![CleanShot 2024-09-09 at 09 22 14](https://github.com/user-attachments/assets/63b7852d-8d85-4e81-94ea-7dfc887789fd)

![CleanShot 2024-09-09 at 09 22 18](https://github.com/user-attachments/assets/2971428e-8607-45f1-a9b4-d46aa250460c)

> Ideally I guess some sort of an alert space that would be displayed on top?

That could work, maybe one or both of these?

![CleanShot 2024-09-09 at 09 23 18](https://github.com/user-attachments/assets/ebdf9014-345b-444d-9a4b-de6ea2b8f3e7)

> How would you like it to be configured?

Maybe something like... 

```ruby
Karafka::Web.setup do |config|
  config.environment_disamguitator.text = ENV["RAILS_ENV"]
  config.environment_disamguitator.color = case ENV["RAILS_ENV"]
  when "development" then :blue
  when "production" then :red
  # nil implies nothing extra?
  end
end
```

Intentionally bad name chose because I can't think of a better way 😅  I could imagine the railtie setting those, while allowing someone (like us) to override.

**Comment by mensfeld** [comment]
yeah that's a good idea. Let me iterate over it and get back to you
