### ISSUE TITLE
Mask SASL credentials in topic routing view

### ISSUE THREAD

**Issue by vadim-handy** [karafka/karafka-web#46]
## Is your feature request related to a problem? Please describe.

When inspecting routing details for a topic, the view exposes all SASL credentials. The end user should be responsible for putting the web ui ideally behind a VPN & 2FA Auth. However, even then having cluster credentials exposed in plain-text isn't ideal if they're not serving a purpose.

## Describe the solution you'd like

1. The [_details partial of a topic's show page](https://github.com/karafka/karafka-web/blob/master/lib/karafka/web/ui/views/routing/_detail.erb#L8) additionally filters for 'sasl' 

```ruby
        <% if k2.to_s.include?('ssl') || k2.to_s.include?('sasl')  %>
          ***
        <% else %>
          <%= v2 %>
        <% end %>
```

## Describe alternatives you've considered

This seemed like the simplest approach for now unless there are plans for configurable masking settings: 
1.  Configurable regex or keys to match for topic routing show details
2.  Configurable regex or keys to match for topic explore details. e.g. Deeply scan a topic payload in the show tab to exclude values that contain PII (e.g. email, address => '***')

I can turn the above into a separate feature request (topic payload masking)

## Additional context

<img width="1157" alt="Screen Shot 2023-04-04 at 11 13 16 AM" src="https://user-images.githubusercontent.com/79860672/229837934-7a65053b-e121-4e13-9542-af1de5641aed.png">

**Comment by mensfeld** [comment]
True. This should actually be considered a bug.

**Comment by mensfeld** [comment]
> I can turn the above into a separate feature request (topic payload masking)

Pleas do, so far I masked the sasl details.
