### ISSUE TITLE
CSS Content Display: None?

### ISSUE THREAD

**Issue by zacheryph** [karafka/karafka-web#55]
## Expected behavior

The Web UI to be viewable?

## Actual behavior

The css states `#content { display: none; }`. The only thing that gets displayed is the banner to subscribe to karafka pro.

> https://github.com/karafka/karafka-web/blob/master/lib/karafka/web/ui/public/stylesheets/application.css#L7

## Steps to reproduce the problem

Install Web, Attempt to view UI

## Your setup details

```
Karafka version: 2.0.39
Ruby version: ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [arm64-darwin22]
Rdkafka version: 0.12.1
Consumer groups count: 3
Subscription groups count: 3
Workers count: 5
Application client id: next
Boot file: ./config/karafka.rb
Environment: development
License: LGPL-3.0
```

**Comment by mensfeld** [comment]
:wave: what browser? do you have any JS blocking stuff or adblock? this is hidden to prevent flickering and displayed via JS.

**Comment by zacheryph** [comment]
💡 This appears to be CSP related. Using script-src with `strict_dynamic` and a nonce is preventing karafka-web from loading its javascript.  It appears Sidekiq handles this by overriding with its own CSP headers but Rails seems to still send them for Karafka.

> Reference
> https://github.com/sidekiq/sidekiq/blob/ae6ca119a5478e170ee55dbae6a79a29e3a8fd9a/lib/sidekiq/web/application.rb#L8

**Comment by mensfeld** [comment]
Thank you for the details, somehow I assued Roda dealt with this out of the box but it seems it has a plugin for this. I will fix this in the upcoming week

**Comment by mensfeld** [comment]
@zacheryph would you mind testing this branch? https://github.com/karafka/karafka-web/issues/55 - I used exactly same set of CSPs as Sidekiq

**Comment by zacheryph** [comment]
@mensfeld happy to say this works like a charm :)

Thank you for all your work on Karafka.

**Comment by mensfeld** [comment]
Awesome. I will craft the release tops at the beginning of next week. Please don't forget to :star:  https://github.com/karafka/karafka if you enjoy working with Karafka. It helps me grow the community.

**Comment by mensfeld** [comment]
@zacheryph released: https://rubygems.org/gems/karafka-web/versions/0.5.1
